/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import eventos.IEvento;
import java.util.List;
import red.cliente.IClienteRed;

/**
 *
 * @author ReneEzequiel23 & EdgarAcevedoAcosta
 */
public class PantallaLobby extends javax.swing.JFrame implements eventos.IEventoListener {

    String miNombre;
    private IClienteRed cliente;
    private eventos.IEventBus busLocal;
    private boolean actualizandoUI = false;
    private boolean partidaIniciada = false;

    /**
     * Creates new form PantallaLobby
     */
    public PantallaLobby(IClienteRed cliente, eventos.IEventBus busLocal, String idJugadorLocal) {
        this.cliente = cliente;
        this.busLocal = busLocal;
        this.miNombre = idJugadorLocal;

        initComponents();
        panelSolicitud.setVisible(false);
        // ¡LA CLAVE ESTABA AQUÍ! Suscribirse a los DOS eventos
        this.busLocal.suscribir(eventos.tipos.EventoEstadoLobby.TIPO, this); // Para actualizar la lista
        this.busLocal.suscribir(eventos.tipos.EventoEstadoMesa.TIPO, this);  // Para saltar al juego
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarPartida = new javax.swing.JButton();
        panelListaJugadores = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jCheckBoxListo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        lblIcono1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        jCheckBoxListo1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        lblIcono2 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        jCheckBoxListo2 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        lblIcono3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        jCheckBoxListo3 = new javax.swing.JCheckBox();
        panelSolicitud = new javax.swing.JPanel();
        btnRechazarInvitacion = new javax.swing.JButton();
        btnAceptarInvitación = new javax.swing.JButton();
        lblTextoSolicitud = new javax.swing.JLabel();
        lblCodigoSala = new javax.swing.JLabel();
        btnConfiguración = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciarPartida.setText("IniciarPartida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        panelListaJugadores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelListaJugadores.setLayout(new java.awt.GridLayout(4, 1));

        lblIcono.setText("Icono");

        lblNombre.setText("Nombre");

        jCheckBoxListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono)
                .addGap(33, 33, 33)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jCheckBoxListo)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxListo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIcono)
                        .addComponent(lblNombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelListaJugadores.add(jPanel3);

        lblIcono1.setText("Icono");

        lblNombre1.setText("Nombre");

        jCheckBoxListo1.setEnabled(false);
        jCheckBoxListo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxListo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono1)
                .addGap(33, 33, 33)
                .addComponent(lblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jCheckBoxListo1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxListo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIcono1)
                        .addComponent(lblNombre1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelListaJugadores.add(jPanel4);

        lblIcono2.setText("Icono");

        lblNombre2.setText("Nombre");

        jCheckBoxListo2.setEnabled(false);
        jCheckBoxListo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxListo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono2)
                .addGap(33, 33, 33)
                .addComponent(lblNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jCheckBoxListo2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxListo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIcono2)
                        .addComponent(lblNombre2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelListaJugadores.add(jPanel5);

        lblIcono3.setText("Icono");

        lblNombre3.setText("Nombre");

        jCheckBoxListo3.setEnabled(false);
        jCheckBoxListo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxListo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono3)
                .addGap(33, 33, 33)
                .addComponent(lblNombre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jCheckBoxListo3)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxListo3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIcono3)
                        .addComponent(lblNombre3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelListaJugadores.add(jPanel6);

        panelSolicitud.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));

        btnRechazarInvitacion.setText("Rechazar");

        btnAceptarInvitación.setText("Aceptar");
        btnAceptarInvitación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarInvitaciónActionPerformed(evt);
            }
        });

        lblTextoSolicitud.setText("Juanito 777 desea unirse");

        javax.swing.GroupLayout panelSolicitudLayout = new javax.swing.GroupLayout(panelSolicitud);
        panelSolicitud.setLayout(panelSolicitudLayout);
        panelSolicitudLayout.setHorizontalGroup(
            panelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSolicitudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAceptarInvitación)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnRechazarInvitacion)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSolicitudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTextoSolicitud)
                .addGap(34, 34, 34))
        );
        panelSolicitudLayout.setVerticalGroup(
            panelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSolicitudLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTextoSolicitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panelSolicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRechazarInvitacion)
                    .addComponent(btnAceptarInvitación)))
        );

        lblCodigoSala.setText("Codigo de sala: XPLASF");

        btnConfiguración.setText("Configuracion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelListaJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnConfiguración)
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblCodigoSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIniciarPartida)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(panelListaJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfiguración)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoSala)
                    .addComponent(btnIniciarPartida))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        dtos.ComandoJugadorDTO comando = new dtos.ComandoJugadorDTO(
                this.miNombre,
                dtos.TipoAccion.SOLICITAR_INICIO, // o MARCAR_LISTO
                null, null, null
        );

        // En lugar del EventBus, llamamos directo al cliente (igual que en PantallaPartida)
        this.cliente.enviarComando(comando);
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void jCheckBoxListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxListoActionPerformed
        // TODO add your handling code here:
        enviarComandoListo(jCheckBoxListo);
    }//GEN-LAST:event_jCheckBoxListoActionPerformed

    private void jCheckBoxListo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxListo1ActionPerformed
        // TODO add your handling code here:
        enviarComandoListo(jCheckBoxListo1);
    }//GEN-LAST:event_jCheckBoxListo1ActionPerformed

    private void jCheckBoxListo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxListo2ActionPerformed
        // TODO add your handling code here:
        enviarComandoListo(jCheckBoxListo2);
    }//GEN-LAST:event_jCheckBoxListo2ActionPerformed

    private void jCheckBoxListo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxListo3ActionPerformed
        // TODO add your handling code here:
        enviarComandoListo(jCheckBoxListo3);
    }//GEN-LAST:event_jCheckBoxListo3ActionPerformed

    private void btnAceptarInvitaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarInvitaciónActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAceptarInvitaciónActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarInvitación;
    private javax.swing.JButton btnConfiguración;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnRechazarInvitacion;
    private javax.swing.JCheckBox jCheckBoxListo;
    private javax.swing.JCheckBox jCheckBoxListo1;
    private javax.swing.JCheckBox jCheckBoxListo2;
    private javax.swing.JCheckBox jCheckBoxListo3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCodigoSala;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblIcono3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblTextoSolicitud;
    private javax.swing.JPanel panelListaJugadores;
    private javax.swing.JPanel panelSolicitud;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onEvent(eventos.IEvento evento) {
        System.out.println("[PantallaLobby] Evento recibido: " + evento.getTipoEvento()); // Para depurar en consola

        // CASO 1: Actualización de los jugadores en el Lobby
        if (evento instanceof eventos.tipos.EventoEstadoLobby) {
            dtos.EstadoLobbyDTO estado = ((eventos.tipos.EventoEstadoLobby) evento).getEstadoLobbyDTO();

            // Forzamos la actualización visual en el hilo de la interfaz
            javax.swing.SwingUtilities.invokeLater(() -> {
                actualizarInterfazLobby(estado);
            });
        } // CASO 2: El juego ha iniciado
        else if (evento instanceof eventos.tipos.EventoEstadoMesa) {
        // ¡EL CERROJO! Si ya iniciamos una vez, ignoramos cualquier evento duplicado
        if (partidaIniciada) return;
        
        partidaIniciada = true; // Marcamos que ya estamos en proceso de cambio
        
        dtos.EstadoMesaDTO mesaInicial = ((eventos.tipos.EventoEstadoMesa) evento).getEstadoDTO();

        javax.swing.SwingUtilities.invokeLater(() -> {
            vista.PantallaPartida partidaUI = new vista.PantallaPartida(this.cliente, this.busLocal, this.miNombre, mesaInicial);
            partidaUI.setVisible(true);

            // Desuscripción y cierre
            this.busLocal.desuscribir(eventos.tipos.EventoEstadoLobby.TIPO, this);
            this.busLocal.desuscribir(eventos.tipos.EventoEstadoMesa.TIPO, this);
            this.dispose();
        });
    }
    }

    /**
     * Mapea los datos del DTO hacia tus componentes de NetBeans (jPanel3,
     * jPanel4, etc.)
     */
    private void actualizarInterfazLobby(dtos.EstadoLobbyDTO estado) {
        // Actualizamos el código de sala
        actualizandoUI = true;
        this.lblCodigoSala.setText("Codigo de sala: " + estado.getCodigoSala());

        List<dtos.JugadorLobbyDTO> lista = estado.getJugadoresEnSala();

        // Arreglo con tus paneles de fila para iterar fácilmente
        javax.swing.JPanel[] filas = {jPanel3, jPanel4, jPanel5, jPanel6};

        // Arreglo con tus labels de nombre
        javax.swing.JLabel[] nombres = {lblNombre, lblNombre1, lblNombre2, lblNombre3};

        // Arreglo con tus checkboxes
        javax.swing.JCheckBox[] checks = {jCheckBoxListo, jCheckBoxListo1, jCheckBoxListo2, jCheckBoxListo3};

        boolean soyHost = false; // Bandera para saber si tengo el poder

        for (int i = 0; i < filas.length; i++) {
            if (i < lista.size()) {
                dtos.JugadorLobbyDTO jDTO = lista.get(i);
                filas[i].setVisible(true);
                nombres[i].setText(jDTO.getNombre() + (jDTO.isEsHost() ? " (Host)" : ""));

                // Actualizamos visualmente la palomita
                checks[i].setSelected(jDTO.isEstaListo());

                // ¿Este jugador soy yo?
                if (jDTO.getNombre().equals(this.miNombre)) {
                    checks[i].setEnabled(true); // Solo puedo darle clic a MI casilla
                    if (jDTO.isEsHost()) {
                        soyHost = true; // Descubrí que yo soy el host
                    }
                } else {
                    checks[i].setEnabled(false); // Bloqueo las casillas de los demás
                }

            } else {
                filas[i].setVisible(false);
            }
        }

        // Si no soy el host, me desaparecen los botones de control
        btnIniciarPartida.setVisible(soyHost);
        btnConfiguración.setVisible(soyHost);
        actualizandoUI = false;
    }
    
    private void enviarComandoListo(javax.swing.JCheckBox miCheck) {
        // Si el programa está pintando la palomita, abortamos el envío a la red.
        if (actualizandoUI) return; 

        dtos.TipoAccion accionActual = miCheck.isSelected()
                ? dtos.TipoAccion.MARCAR_LISTO
                : dtos.TipoAccion.DESMARCAR_LISTO;

        dtos.ComandoJugadorDTO comando = new dtos.ComandoJugadorDTO(
                this.miNombre, accionActual, null, null, null
        );

        this.cliente.enviarComando(comando);
    }
}
