/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.LobbyVistaControlador;
import eventos.EventBus;
import eventos.IEventBus;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import red.cliente.ClienteUNO;

/**
 *
 * @author edgar
 */
public class PantallaInicio extends javax.swing.JFrame {
    private String nombreElegido;
    private int avatar;
    private IEventBus busLocal;
    private ClienteUNO clienteRed;

        

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
        // Usamos el Bus Local para la comunicación interna entre hilos
        busLocal = new EventBus();
        // Inicializamos el cliente de red (implementa IClienteRed)
        clienteRed = new ClienteUNO(busLocal);
        nombreElegido="DefaultName";
        avatar=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        btnUnirseParida = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UNO");

        btnCrearPartida.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.setPreferredSize(new java.awt.Dimension(600, 23));
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });

        btnUnirseParida.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnUnirseParida.setText("Unirse a una Partida");
        btnUnirseParida.setPreferredSize(new java.awt.Dimension(600, 23));
        btnUnirseParida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseParidaActionPerformed(evt);
            }
        });

        btnConfig.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnConfig.setText("Configuración");
        btnConfig.setPreferredSize(new java.awt.Dimension(600, 23));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUnirseParida, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnCrearPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnUnirseParida, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        PantallaConfiguracion frm=new PantallaConfiguracion(nombreElegido,avatar);
        frm.setVisible(true);
        
        frm.btnCancelar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
              nombreElegido=frm.devolverNombre();
              avatar=frm.devolverAvatar();
              frm.dispose();
            }
        
        });
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnUnirseParidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseParidaActionPerformed
        // TODO add your handling code here:
        PantallaBusqueda frm=new PantallaBusqueda(nombreElegido,avatar);
        frm.setVisible(true);
    }//GEN-LAST:event_btnUnirseParidaActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        // TODO add your handling code here:
        if(nombreElegido=="DefaultName"){
            JOptionPane.showConfirmDialog(this, "No puedes jugar con este nombre de jugador", "Error!", JOptionPane.OK_OPTION);
        }else{
            // 3. Inicializamos el Controlador de la Vista (Cerebro)
            // Inyectamos la red y el bus al controlador
            LobbyVistaControlador lobbyCtrl = new LobbyVistaControlador(busLocal, nombreElegido);
            // 4. Inicializamos la Vista pasándole el controlador y el nombre
            vista.PantallaLobby lobbyVista = new vista.PantallaLobby(lobbyCtrl, nombreElegido);
            Thread hiloRed = new Thread(clienteRed);
            hiloRed.start();

            java.awt.EventQueue.invokeLater(() -> {
                lobbyVista.setVisible(true);
                lobbyVista.setLocationRelativeTo(null);

                // Automatización: Esperamos 300ms para que el Socket se estabilice 
                // y luego enviamos el DTO de entrada automáticamente.
                new java.util.Timer().schedule(new java.util.TimerTask() {
                    @Override
                    public void run() {
                        System.out.println("[Main] Ejecutando saludo automático...");
                        lobbyCtrl.entrarAlLobby();
                    }
                }, 300);
            });

            System.out.println("[Main] Cliente " + nombreElegido + " iniciado y listo.");
        }
    }//GEN-LAST:event_btnCrearPartidaActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnUnirseParida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
